version: "3.8"

services:
  students:
    image: postgres:10.3
    restart: always
    volumes:
      - ./db/up.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"